# Generated by Django 5.0.3 on 2024-07-09 16:23

import autoslug.fields
import django.db.models.deletion
import songs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва категорії')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
            ],
            options={
                'verbose_name': 'Категорія(ю)',
                'verbose_name_plural': 'Категорії',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='user')),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='songs.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва тєгу')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/%Y/', verbose_name='Аватарка')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Song_of_the_Day',
            fields=[
                ('title', models.CharField(max_length=150, verbose_name='Назва пісні')),
                ('album', models.CharField(max_length=150, verbose_name='Назва альбому')),
                ('artist', models.CharField(max_length=150, verbose_name='Назва виконавця')),
                ('cover', models.URLField(max_length=500, verbose_name='Обкладинка')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Рік випуску')),
                ('link', models.URLField(verbose_name='Адреса')),
                ('description', models.TextField(blank=True, verbose_name='Особистий опис')),
                ('emotion', models.CharField(blank=True, max_length=10, verbose_name='Емоційка')),
                ('day', models.DateField(verbose_name='День')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опублікувати')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Було додано')),
                ('profile', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='songs.profile', verbose_name='Профіль')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=songs.models.populate_slug, slugify=songs.models.custom_slugify, unique_with=['day'])),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Дні_пісень', to='songs.category', verbose_name='Категорія')),
                ('tags', models.ManyToManyField(blank=True, related_name='Дні_пісень', to='songs.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Пісня(ю) дня',
                'verbose_name_plural': 'Пісні дня',
                'ordering': ['profile', '-day'],
            },
        ),
    ]
